# Generated by Django 5.1.6 on 2025-02-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
