# Generated by Django 5.1.6 on 2025-02-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_category_created_at_category_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='default-category', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sluge',
            field=models.SlugField(default='prduct_name', max_length=255, unique=True),
        ),
    ]
